//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.24 at 03:56:01 PM CEST 
//


package com.nex.gamebook.xsd;

import ae.javax.xml.bind.annotation.XmlEnum;
import ae.javax.xml.bind.annotation.XmlEnumValue;
import ae.javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for attrType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="attrType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="health"/>
 *     &lt;enumeration value="defense"/>
 *     &lt;enumeration value="luck"/>
 *     &lt;enumeration value="skill"/>
 *     &lt;enumeration value="attack"/>
 *     &lt;enumeration value="damage"/>
 *     &lt;enumeration value="skillpower"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "attrType")
@XmlEnum
public enum AttrType {

    @XmlEnumValue("health")
    HEALTH("health"),
    @XmlEnumValue("defense")
    DEFENSE("defense"),
    @XmlEnumValue("luck")
    LUCK("luck"),
    @XmlEnumValue("skill")
    SKILL("skill"),
    @XmlEnumValue("attack")
    ATTACK("attack"),
    @XmlEnumValue("damage")
    DAMAGE("damage"),
    @XmlEnumValue("skillpower")
    SKILLPOWER("skillpower");
    private final String value;

    AttrType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AttrType fromValue(String v) {
        for (AttrType c: AttrType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
