//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.24 at 03:56:01 PM CEST 
//


package com.nex.gamebook.xsd;

import ae.javax.xml.bind.annotation.XmlEnum;
import ae.javax.xml.bind.annotation.XmlEnumValue;
import ae.javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for enemyLevelType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="enemyLevelType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="boss"/>
 *     &lt;enumeration value="minion"/>
 *     &lt;enumeration value="creature"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "enemyLevelType")
@XmlEnum
public enum EnemyLevelType {

    @XmlEnumValue("boss")
    BOSS("boss"),
    @XmlEnumValue("minion")
    MINION("minion"),
    @XmlEnumValue("creature")
    CREATURE("creature");
    private final String value;

    EnemyLevelType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EnemyLevelType fromValue(String v) {
        for (EnemyLevelType c: EnemyLevelType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
