//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.24 at 03:56:01 PM CEST 
//


package com.nex.gamebook.xsd;

import ae.javax.xml.bind.annotation.XmlAccessType;
import ae.javax.xml.bind.annotation.XmlAccessorType;
import ae.javax.xml.bind.annotation.XmlAttribute;
import ae.javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for enemyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="enemyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="skills" type="{}skillsRefType" minOccurs="0"/>
 *         &lt;element name="skillPower" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="health" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="defense" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="skill" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="luck" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="attack" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="baseDamage" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="difficulty" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="xpcoeff" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="type" type="{}enemyLevelType" />
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "enemyType", propOrder = {
    "skills",
    "skillPower",
    "health",
    "defense",
    "skill",
    "luck",
    "attack",
    "baseDamage"
})
public class EnemyType {

    protected SkillsRefType skills;
    protected Integer skillPower;
    protected int health;
    protected int defense;
    protected int skill;
    protected int luck;
    protected int attack;
    protected Integer baseDamage;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "difficulty")
    protected Integer difficulty;
    @XmlAttribute(name = "xpcoeff")
    protected Float xpcoeff;
    @XmlAttribute(name = "type")
    protected EnemyLevelType type;
    @XmlAttribute(name = "id", required = true)
    protected String id;

    /**
     * Gets the value of the skills property.
     * 
     * @return
     *     possible object is
     *     {@link SkillsRefType }
     *     
     */
    public SkillsRefType getSkills() {
        return skills;
    }

    /**
     * Sets the value of the skills property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkillsRefType }
     *     
     */
    public void setSkills(SkillsRefType value) {
        this.skills = value;
    }

    /**
     * Gets the value of the skillPower property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSkillPower() {
        return skillPower;
    }

    /**
     * Sets the value of the skillPower property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSkillPower(Integer value) {
        this.skillPower = value;
    }

    /**
     * Gets the value of the health property.
     * 
     */
    public int getHealth() {
        return health;
    }

    /**
     * Sets the value of the health property.
     * 
     */
    public void setHealth(int value) {
        this.health = value;
    }

    /**
     * Gets the value of the defense property.
     * 
     */
    public int getDefense() {
        return defense;
    }

    /**
     * Sets the value of the defense property.
     * 
     */
    public void setDefense(int value) {
        this.defense = value;
    }

    /**
     * Gets the value of the skill property.
     * 
     */
    public int getSkill() {
        return skill;
    }

    /**
     * Sets the value of the skill property.
     * 
     */
    public void setSkill(int value) {
        this.skill = value;
    }

    /**
     * Gets the value of the luck property.
     * 
     */
    public int getLuck() {
        return luck;
    }

    /**
     * Sets the value of the luck property.
     * 
     */
    public void setLuck(int value) {
        this.luck = value;
    }

    /**
     * Gets the value of the attack property.
     * 
     */
    public int getAttack() {
        return attack;
    }

    /**
     * Sets the value of the attack property.
     * 
     */
    public void setAttack(int value) {
        this.attack = value;
    }

    /**
     * Gets the value of the baseDamage property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBaseDamage() {
        return baseDamage;
    }

    /**
     * Sets the value of the baseDamage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBaseDamage(Integer value) {
        this.baseDamage = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the difficulty property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDifficulty() {
        return difficulty;
    }

    /**
     * Sets the value of the difficulty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDifficulty(Integer value) {
        this.difficulty = value;
    }

    /**
     * Gets the value of the xpcoeff property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getXpcoeff() {
        return xpcoeff;
    }

    /**
     * Sets the value of the xpcoeff property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setXpcoeff(Float value) {
        this.xpcoeff = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link EnemyLevelType }
     *     
     */
    public EnemyLevelType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnemyLevelType }
     *     
     */
    public void setType(EnemyLevelType value) {
        this.type = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
