//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.24 at 03:56:01 PM CEST 
//


package com.nex.gamebook.xsd;

import ae.javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.nex.gamebook.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.nex.gamebook.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Story }
     * 
     */
    public Story createStory() {
        return new Story();
    }

    /**
     * Create an instance of {@link IncludeType }
     * 
     */
    public IncludeType createIncludeType() {
        return new IncludeType();
    }

    /**
     * Create an instance of {@link CharactersType }
     * 
     */
    public CharactersType createCharactersType() {
        return new CharactersType();
    }

    /**
     * Create an instance of {@link EnemiesType }
     * 
     */
    public EnemiesType createEnemiesType() {
        return new EnemiesType();
    }

    /**
     * Create an instance of {@link SectionsType }
     * 
     */
    public SectionsType createSectionsType() {
        return new SectionsType();
    }

    /**
     * Create an instance of {@link Skills }
     * 
     */
    public Skills createSkills() {
        return new Skills();
    }

    /**
     * Create an instance of {@link EnemyReference }
     * 
     */
    public EnemyReference createEnemyReference() {
        return new EnemyReference();
    }

    /**
     * Create an instance of {@link SkillReference }
     * 
     */
    public SkillReference createSkillReference() {
        return new SkillReference();
    }

    /**
     * Create an instance of {@link EnemyType }
     * 
     */
    public EnemyType createEnemyType() {
        return new EnemyType();
    }

    /**
     * Create an instance of {@link SkillsRefType }
     * 
     */
    public SkillsRefType createSkillsRefType() {
        return new SkillsRefType();
    }

    /**
     * Create an instance of {@link CharacterType }
     * 
     */
    public CharacterType createCharacterType() {
        return new CharacterType();
    }

    /**
     * Create an instance of {@link Skill }
     * 
     */
    public Skill createSkill() {
        return new Skill();
    }

    /**
     * Create an instance of {@link OptionsType }
     * 
     */
    public OptionsType createOptionsType() {
        return new OptionsType();
    }

    /**
     * Create an instance of {@link BonusType }
     * 
     */
    public BonusType createBonusType() {
        return new BonusType();
    }

    /**
     * Create an instance of {@link SectionType }
     * 
     */
    public SectionType createSectionType() {
        return new SectionType();
    }

    /**
     * Create an instance of {@link EnemiesRefType }
     * 
     */
    public EnemiesRefType createEnemiesRefType() {
        return new EnemiesRefType();
    }

    /**
     * Create an instance of {@link BonusesType }
     * 
     */
    public BonusesType createBonusesType() {
        return new BonusesType();
    }

    /**
     * Create an instance of {@link OptionType }
     * 
     */
    public OptionType createOptionType() {
        return new OptionType();
    }

}
