//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.24 at 03:56:01 PM CEST 
//


package com.nex.gamebook.xsd;

import ae.javax.xml.bind.annotation.XmlAccessType;
import ae.javax.xml.bind.annotation.XmlAccessorType;
import ae.javax.xml.bind.annotation.XmlAttribute;
import ae.javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for optionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="optionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="section" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="text" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="disableWhenSelected" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="luckAspect" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="skill" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "optionType")
public class OptionType {

    @XmlAttribute(name = "section", required = true)
    protected int section;
    @XmlAttribute(name = "text", required = true)
    protected String text;
    @XmlAttribute(name = "disableWhenSelected")
    protected Boolean disableWhenSelected;
    @XmlAttribute(name = "luckAspect")
    protected Boolean luckAspect;
    @XmlAttribute(name = "skill")
    protected Integer skill;

    /**
     * Gets the value of the section property.
     * 
     */
    public int getSection() {
        return section;
    }

    /**
     * Sets the value of the section property.
     * 
     */
    public void setSection(int value) {
        this.section = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the disableWhenSelected property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDisableWhenSelected() {
        return disableWhenSelected;
    }

    /**
     * Sets the value of the disableWhenSelected property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDisableWhenSelected(Boolean value) {
        this.disableWhenSelected = value;
    }

    /**
     * Gets the value of the luckAspect property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLuckAspect() {
        return luckAspect;
    }

    /**
     * Sets the value of the luckAspect property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLuckAspect(Boolean value) {
        this.luckAspect = value;
    }

    /**
     * Gets the value of the skill property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSkill() {
        return skill;
    }

    /**
     * Sets the value of the skill property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSkill(Integer value) {
        this.skill = value;
    }

}
