//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.24 at 03:56:01 PM CEST 
//


package com.nex.gamebook.xsd;

import ae.javax.xml.bind.annotation.XmlEnum;
import ae.javax.xml.bind.annotation.XmlEnumValue;
import ae.javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for passiveSkills.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="passiveSkills">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="passiveDodgeIsSkill"/>
 *     &lt;enumeration value="passiveLeech"/>
 *     &lt;enumeration value="passiveBoost"/>
 *     &lt;enumeration value="passiveLuckIsSkillpower"/>
 *     &lt;enumeration value="passiveCriticalSkills"/>
 *     &lt;enumeration value="passiveHealthForSkillpower"/>
 *     &lt;enumeration value="passiveAttackBuff"/>
 *     &lt;enumeration value="passiveHealthForAttack"/>
 *     &lt;enumeration value="passiveHealthIsDefense"/>
 *     &lt;enumeration value="passiveHealthIncrease"/>
 *     &lt;enumeration value="passiveDefenseBuff"/>
 *     &lt;enumeration value="passiveDefenseIsAttack"/>
 *     &lt;enumeration value="passiveAOE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "passiveSkills")
@XmlEnum
public enum PassiveSkills {

    @XmlEnumValue("passiveDodgeIsSkill")
    PASSIVE_DODGE_IS_SKILL("passiveDodgeIsSkill"),
    @XmlEnumValue("passiveLeech")
    PASSIVE_LEECH("passiveLeech"),
    @XmlEnumValue("passiveBoost")
    PASSIVE_BOOST("passiveBoost"),
    @XmlEnumValue("passiveLuckIsSkillpower")
    PASSIVE_LUCK_IS_SKILLPOWER("passiveLuckIsSkillpower"),
    @XmlEnumValue("passiveCriticalSkills")
    PASSIVE_CRITICAL_SKILLS("passiveCriticalSkills"),
    @XmlEnumValue("passiveHealthForSkillpower")
    PASSIVE_HEALTH_FOR_SKILLPOWER("passiveHealthForSkillpower"),
    @XmlEnumValue("passiveAttackBuff")
    PASSIVE_ATTACK_BUFF("passiveAttackBuff"),
    @XmlEnumValue("passiveHealthForAttack")
    PASSIVE_HEALTH_FOR_ATTACK("passiveHealthForAttack"),
    @XmlEnumValue("passiveHealthIsDefense")
    PASSIVE_HEALTH_IS_DEFENSE("passiveHealthIsDefense"),
    @XmlEnumValue("passiveHealthIncrease")
    PASSIVE_HEALTH_INCREASE("passiveHealthIncrease"),
    @XmlEnumValue("passiveDefenseBuff")
    PASSIVE_DEFENSE_BUFF("passiveDefenseBuff"),
    @XmlEnumValue("passiveDefenseIsAttack")
    PASSIVE_DEFENSE_IS_ATTACK("passiveDefenseIsAttack"),
    @XmlEnumValue("passiveAOE")
    PASSIVE_AOE("passiveAOE");
    private final String value;

    PassiveSkills(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PassiveSkills fromValue(String v) {
        for (PassiveSkills c: PassiveSkills.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
