//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.24 at 03:56:01 PM CEST 
//


package com.nex.gamebook.xsd;

import ae.javax.xml.bind.annotation.XmlAccessType;
import ae.javax.xml.bind.annotation.XmlAccessorType;
import ae.javax.xml.bind.annotation.XmlAttribute;
import ae.javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for skill complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="skill">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="skillName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="attempts" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="turns" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="levelRequired" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="coeff" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="increase" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="condition" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="beforeEnemySkill" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="onEndOfRound" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="beforeEnemyAttack" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="afterEnemyAttack" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="afterNormalAttack" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="permanent" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="type" type="{}attrType" />
 *       &lt;attribute name="proprietarySkill" type="{}proprietarySkill" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "skill")
public class Skill {

    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "skillName", required = true)
    protected String skillName;
    @XmlAttribute(name = "attempts")
    protected Integer attempts;
    @XmlAttribute(name = "turns")
    protected Integer turns;
    @XmlAttribute(name = "levelRequired", required = true)
    protected int levelRequired;
    @XmlAttribute(name = "coeff")
    protected Float coeff;
    @XmlAttribute(name = "increase")
    protected Boolean increase;
    @XmlAttribute(name = "condition")
    protected Boolean condition;
    @XmlAttribute(name = "beforeEnemySkill")
    protected Boolean beforeEnemySkill;
    @XmlAttribute(name = "onEndOfRound")
    protected Boolean onEndOfRound;
    @XmlAttribute(name = "beforeEnemyAttack")
    protected Boolean beforeEnemyAttack;
    @XmlAttribute(name = "afterEnemyAttack")
    protected Boolean afterEnemyAttack;
    @XmlAttribute(name = "afterNormalAttack")
    protected Boolean afterNormalAttack;
    @XmlAttribute(name = "permanent")
    protected Boolean permanent;
    @XmlAttribute(name = "type")
    protected AttrType type;
    @XmlAttribute(name = "proprietarySkill")
    protected ProprietarySkill proprietarySkill;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the skillName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkillName() {
        return skillName;
    }

    /**
     * Sets the value of the skillName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkillName(String value) {
        this.skillName = value;
    }

    /**
     * Gets the value of the attempts property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAttempts() {
        return attempts;
    }

    /**
     * Sets the value of the attempts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAttempts(Integer value) {
        this.attempts = value;
    }

    /**
     * Gets the value of the turns property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTurns() {
        return turns;
    }

    /**
     * Sets the value of the turns property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTurns(Integer value) {
        this.turns = value;
    }

    /**
     * Gets the value of the levelRequired property.
     * 
     */
    public int getLevelRequired() {
        return levelRequired;
    }

    /**
     * Sets the value of the levelRequired property.
     * 
     */
    public void setLevelRequired(int value) {
        this.levelRequired = value;
    }

    /**
     * Gets the value of the coeff property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getCoeff() {
        return coeff;
    }

    /**
     * Sets the value of the coeff property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setCoeff(Float value) {
        this.coeff = value;
    }

    /**
     * Gets the value of the increase property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncrease() {
        return increase;
    }

    /**
     * Sets the value of the increase property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncrease(Boolean value) {
        this.increase = value;
    }

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCondition(Boolean value) {
        this.condition = value;
    }

    /**
     * Gets the value of the beforeEnemySkill property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBeforeEnemySkill() {
        return beforeEnemySkill;
    }

    /**
     * Sets the value of the beforeEnemySkill property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBeforeEnemySkill(Boolean value) {
        this.beforeEnemySkill = value;
    }

    /**
     * Gets the value of the onEndOfRound property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOnEndOfRound() {
        return onEndOfRound;
    }

    /**
     * Sets the value of the onEndOfRound property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOnEndOfRound(Boolean value) {
        this.onEndOfRound = value;
    }

    /**
     * Gets the value of the beforeEnemyAttack property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBeforeEnemyAttack() {
        return beforeEnemyAttack;
    }

    /**
     * Sets the value of the beforeEnemyAttack property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBeforeEnemyAttack(Boolean value) {
        this.beforeEnemyAttack = value;
    }

    /**
     * Gets the value of the afterEnemyAttack property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAfterEnemyAttack() {
        return afterEnemyAttack;
    }

    /**
     * Sets the value of the afterEnemyAttack property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAfterEnemyAttack(Boolean value) {
        this.afterEnemyAttack = value;
    }

    /**
     * Gets the value of the afterNormalAttack property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAfterNormalAttack() {
        return afterNormalAttack;
    }

    /**
     * Sets the value of the afterNormalAttack property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAfterNormalAttack(Boolean value) {
        this.afterNormalAttack = value;
    }

    /**
     * Gets the value of the permanent property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPermanent() {
        return permanent;
    }

    /**
     * Sets the value of the permanent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPermanent(Boolean value) {
        this.permanent = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link AttrType }
     *     
     */
    public AttrType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttrType }
     *     
     */
    public void setType(AttrType value) {
        this.type = value;
    }

    /**
     * Gets the value of the proprietarySkill property.
     * 
     * @return
     *     possible object is
     *     {@link ProprietarySkill }
     *     
     */
    public ProprietarySkill getProprietarySkill() {
        return proprietarySkill;
    }

    /**
     * Sets the value of the proprietarySkill property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProprietarySkill }
     *     
     */
    public void setProprietarySkill(ProprietarySkill value) {
        this.proprietarySkill = value;
    }

}
